version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 10
    reviewers:
      - "pekral"
    assignees:
      - "pekral"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    reviewers:
      - "pekral"
    assignees:
      - "pekral"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
