#!/usr/bin/env bash
# gather-issue-context.sh — assemble everything needed to work on a Bugsnag
# error into a single agent-readable Markdown context brief.
#
# Builds on load-issue.sh (the Bugsnag data layer) and projects it into a brief:
#   - the error header: class, message, status, severity, occurrence/user counts,
#     context, first/last seen, release stages
#   - the latest event: app version / release stage, the failing request, and the
#     in-project stacktrace frames (the TDD reproduction entry point)
#   - the comments
#   - the linked issues (the mirrored GitHub issue/PR) and an inventory of every
#     external URL found in the message, comments, failing request, and links
#
# Bugsnag errors carry no internal error-to-error links, so — unlike the JIRA /
# GitHub gatherers — there is no recursive traversal: `linkedIssues` point at
# another tracker (GitHub) and are surfaced in the URL inventory for the agent to
# follow with its own tools.
#
# The output is Markdown meant to be read by an AI agent as task context, not a
# Bugsnag / PR comment.
#
# Usage:
#   gather-issue-context.sh <URL|ORG/PROJECT/ERROR_ID>
#
# Requires BUGSNAG_TOKEN the same way load-issue.sh does.
#
# load-issue.sh limits (handled by deferring to the agent, stated in the output):
#   - `linkedIssues` point at GitHub; this script lists them and inventories the
#     URLs but does not cross trackers — the agent loads the linked GitHub issue
#     (e.g. via code-review-github/scripts/gather-issue-context.sh) itself.
#   - external URLs are inventoried, not fetched; the agent follows them
#     honouring the project's outbound-request security rules.
#
# Exit codes:
#   1  usage / argument error
#   2  missing required tool (jq) or missing BUGSNAG_TOKEN
#   3  Bugsnag fetch failed for the error
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: gather-issue-context.sh <URL|ORG_SLUG/PROJECT_SLUG/ERROR_ID>

  URL     a Bugsnag dashboard error URL
  TRIPLE  an org-slug/project-slug/error-id triple

Requires BUGSNAG_TOKEN (Data Access API token).
EOF
}

if [[ $# -ne 1 || -z "${1:-}" ]]; then
  usage
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "gather-issue-context.sh: required tool not found: jq" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ERROR_JSON="$("$SCRIPT_DIR/load-issue.sh" "$1")" || exit $?
if [[ -z "$ERROR_JSON" ]] || ! printf '%s' "$ERROR_JSON" | jq -e '.id' >/dev/null 2>&1; then
  echo "gather-issue-context.sh: failed to load Bugsnag error: $1" >&2
  exit 3
fi

# --- Emit Markdown brief ------------------------------------------------------
printf '%s' "$ERROR_JSON" | jq -r '
  def line(lbl; v): if (v // "") == "" then empty else "- **\(lbl):** \(v)" end;

  "# Bugsnag context: \(.errorClass // .title // "(unknown error)")",
  "",
  "> Generated by `gather-issue-context.sh` as task context.",
  "",
  "## Overview",
  "",
  line("Error class"; .errorClass),
  line("Message"; .message),
  line("Status"; .status),
  line("Severity"; .severity),
  line("Context"; .context),
  line("Occurrences"; (.events // "" | tostring)),
  line("Affected users"; (.users // "" | tostring)),
  line("First seen"; .firstSeen),
  line("Last seen"; .lastSeen),
  line("Release stages"; (.releaseStages // [] | join(", "))),
  line("Project"; (.project.name // .project.slug)),
  line("URL"; .url),
  "",
  ( .latestEvent as $e
    | if $e == null then "_No latest event captured._"
      else
        ( "## Latest event",
          "",
          line("Received at"; $e.receivedAt),
          line("App version"; "\($e.app.version // "?") (\($e.app.releaseStage // "?"))"),
          line("Unhandled"; ($e.unhandled | tostring)),
          line("Request"; (if $e.request == null then null else "\($e.request.httpMethod // "?") \($e.request.url // "?")" end)),
          "",
          ( ($e.stacktrace // []) as $st
            | "### In-project stacktrace frames",
              "",
              ( ([ $st[] | select(.inProject == true) ]) as $ip
                | (if ($ip | length) == 0 then $st else $ip end) as $frames
                | if ($frames | length) == 0 then "_No stacktrace frames._"
                  else ($frames[] | "- `\(.file // "?"):\(.line // "?")` — \(.method // "?")\(if .inProject == true then " *(in project)*" else "" end)")
                  end ) )
        )
      end ),
  "",
  ( (.comments // []) as $c
    | "## Comments (\($c | length))",
      "",
      ( if ($c | length) == 0 then "_No comments._"
        else ( $c | to_entries[]
               | "### [\(.key)] \(.value.author // "?") — \(.value.createdAt // "?")"
                 + "\n\n" + (.value.body // "") )
        end ) ),
  "",
  ( (.linkedIssues // []) as $li
    | if ($li | length) == 0 then empty
      else ( "## Linked issues", "",
             ($li[] | "- \(.type // "link") #\(.number // "?") — \(.url // "?")") )
      end )
'

# --- URL inventory ------------------------------------------------------------
URL_INVENTORY="$(
  printf '%s' "$ERROR_JSON" | jq -r '
    [ (.message // ""),
      ((.comments // [])[].body // ""),
      (.latestEvent.request.url // ""),
      ((.linkedIssues // [])[].url // "") ] | join("\n")' \
    | grep -oE 'https?://[^][:space:]"`<>(){}]+' \
    | sed -E 's/[].,;:?!`)}>"'"'"']+$//' \
    | grep -E '^https?://[^/]+\.[^/]' \
    | sort -u || true
)"

echo
echo "# URL inventory"
echo
if [[ -n "$URL_INVENTORY" ]]; then
  echo "External links found in the message, comments, failing request, and linked issues. The agent fetches their content with its own web tools (recursively when useful), honouring the project's outbound-request security rules:"
  echo
  printf '%s\n' "$URL_INVENTORY" | sed 's/^/- /'
else
  echo "_No external links found._"
fi
echo
echo "---"
echo "## Notes for the agent"
echo "- **Linked GitHub issues/PRs** above are a different tracker — load them with \`skills/code-review-github/scripts/gather-issue-context.sh <URL>\` when you need their full context."
echo "- **External links** above: follow them with your own web tools; continue recursively to a sensible depth when they lead to further relevant sources."
echo "- The in-project stacktrace frames are the entry point for a TDD reproduction of the error."
