name: PHPCS Rules Check

on:
  push:
    paths:
      - 'rules/**'
      - 'rector.php'
      - '.github/workflows/phpcs-rules.yml'
  pull_request:
    paths:
      - 'rules/**'
      - 'rector.php'
      - '.github/workflows/phpcs-rules.yml'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Install pekral/phpcs-rules
        run: composer require --dev pekral/phpcs-rules --no-interaction --no-progress

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=vendor/pekral/phpcs-rules rules/ rector.php 